nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

# packageExtensions:
#   '@walletconnect/iso-crypto@^1.7.8':
#     dependencies:
#       '@walletconnect/encoding': '^1.0.1'
#   '@web3-react/walletconnect@^8.0.35-beta.0':
#     dependencies:
#       '@walletconnect/jsonrpc-http-connection': '^1.0.0'
#       '@walletconnect/jsonrpc-provider': '^1.0.3'
